travis:
  secure:
    BINSTAR_TOKEN: d60wrmXhNGEDfbju47DLxhatpwF0Cpo4ls5UlFElMo2bt39LSm4JwJOF/GqmCdDjNoL7tHy6lbUeaXy/dWaOO5xYhfJnT/GYzdDfsfFjX8Ato9KC+AckqtTodZ3469dXOpM2b1PYMFQtkdSNtWqukOmBPWPOzFz0kGVywV7XhN1+QlukGLnuaFrJ5mEQjsXOFFf/kNNjaLBmh+bee17A+P06pQJS4wtYC3qoCByFC2CCcSRh6ARpBOvhZiNc0dbX/GYqTyRVDWtKIUAGb4fb1KbZMUdg2Byber/VI+IOaQlllGNYwsNT//pIdT18ekmyuAvwH852fWCiUAJ5FSqHhqyfkpSYkyaUngpZG6p+rcm67zqVOXfIw6+Se9hcy5qlPgjfGi9iSGgCAeYgprE8DPmNSq8oVKwSME0jWaUWrWm9UsKgeUgpAMmpTSB7wNH5rbiBzCIWZvlhIa+W8CGXhvjb0+dMIt80cGG39yLLnYlzq/qfYGeXzws5imOwHhMomEVDrjolZC57/PQ6NZMtq2YaHiqGhC4b9R8ue+oGhDJJgZv8u6S8gOKOuDopaf7hUhsT/SaitMUUPASrxhRpH7wP7dgNeD+liqX57msrhvQJx+M7lR/Z7A0tpB1NnKHxMJSwXDkbbwHo9Df5VNhBeIbYaYjFCnTDekVpkIXxQ3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
